### ISSUE TITLE
brainrender-gui does not display anything and throws errors in the console

### ISSUE THREAD

**Issue by anandsku** [brainglobe/brainrender#229] opened 2023-04-24 15:14 UTC
**Describe the bug**
brainrender-gui does not display anything and throws the following errors in the console:

![brainrender_gui_error](https://user-images.githubusercontent.com/43101976/234037607-5d3642dc-74cd-4b5d-8aed-9c1938956139.PNG)

This is how the GUI looks:

![brainrender_gui_error_2](https://user-images.githubusercontent.com/43101976/234037677-35d9e023-3944-4527-a9d6-7c503d5885b3.PNG)

**To Reproduce**
brainrender v: 2.0.5.5
vedo v: 2021.0.5
python v: 3.7.16
anaconda v: custom
OS: Widnows 10

Then tell us the steps to reproduce the behavior:
type brainrender-gui at the terminal

**Expected behavior**
Nothing displays in the brainrender GUI and when you close it, the above error messages show up.

**Screenshots**
Added these in the problem description

**Comment by chongtianyifa** [comment] 2023-05-21 06:13
Any update about this? I got the same error.

**Comment by FedeClaudi** [comment] 2023-05-21 13:23
seems to be the same issue as: https://github.com/brainglobe/brainrender/issues/183

**Comment by chongtianyifa** [comment] 2023-05-27 05:13
No, I tried pip install PyQt5. It did not fix the error:
![image](https://github.com/brainglobe/brainrender/assets/46367566/5134039e-80b7-49f6-9a4c-670ad882ebd2)
Here is my installation and initiation procedure:
conda create -n brainrender python=3.8
conda activate brainrender
pip install -U git+https://github.com/brainglobe/brainrender.git
pip install PySide2
pip install PyQt5
brainrender-gui

**Comment by adamltyson** [comment] 2023-12-21 13:31
Closing as this is a duplicate of #286 and the brainrender GUI will be removed in the next release, in favour of [brainrender-napari](https://github.com/brainglobe/brainrender-napari).

**Closed by adamltyson** 2023-12-21 13:31 UTC
Labels: bug
