### ISSUE TITLE
Improper rendering of mouse brain region - medial habenula

### ISSUE THREAD

**Issue by deepakasaragod** [brainglobe/brainrender#143] opened 2021-02-03 03:21 UTC
Hi there, 

I was trying some example codes with BrainRender. Brain region of our interest is habenula. A simple rendering using `popup_scene.add_brain_region('MH')`  renders medial habenula as a continuous structure bilaterally, which is not true anatomically (Allen brain atlas). This might be an issue with BrainRender. Any insights.  Thank you. 

![Github-issue-brainrender](https://user-images.githubusercontent.com/6326296/106693105-38ead500-6582-11eb-93cc-4a644cb9e7a8.png)

**Comment by FedeClaudi** [comment] 2021-02-03 08:59
Hi, 

Thanks for getting in touch. 

I agree, in the Allen atlas it looks like the MH is not continuous:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/17436313/106722436-dc2d0000-65fd-11eb-8335-9c8e66cde8ba.png">


However, in the allen 3d viewer the mesh for this brain region is like the one in brainrender (brainrender uses the default meshes for this atlas): 
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/17436313/106722518-f961ce80-65fd-11eb-90d8-fff40922502a.png">

I'm not sure what the cause for this discrepancy is, but it does not depend on brainrender. I'm closing this issue as not brainrender related, but do get in touch for any question or clarification

**Closed by FedeClaudi** 2021-02-03 08:59 UTC
Labels: enhancement

**Comment by deepakasaragod** [comment] 2021-02-03 10:14
Thanks @FedeClaudi . Agree with you that it is not a BR issue but Allen Brain issue, presumably some sort of 'downsampling' related, as this issue is noticed towards the posterior sections where the ventricle gets narrower . Will keep in touch in how this issue could be/gets resolved from Allen Brain side.

**Comment by adamltyson** [comment] 2021-02-03 10:48
Hi both, just to chime in - those two atlases are different, the 2D one shown is the "old" 2D reference atlas, and the 3D image is from the new 3D CCFv3. That being said,[ even in the 2D planes of the 3D atlas, the MH is not continuous](https://atlas.brain-map.org/atlas?atlas=602630314#atlas=602630314&plate=576990141&structure=1070&x=5440&y=3744&zoom=-3&resolution=8.00&z=3), so it looks to be an artefact of the smoothing they employ to create smooth, but contiguous 3D structures. 

Have you tried asking the Allen on their [forum](https://community.brain-map.org/)?

**Comment by FedeClaudi** [comment] 2021-02-03 10:50
Thanks Adam, I wasn't aware of that.  I agree it's probably just an artifact: the two halves of the MH come very close in the old atlas too so the meshes might have ben fused.

**Comment by deepakasaragod** [comment] 2021-02-03 10:58
Thanks @adamltyson , @FedeClaudi . I have reported this bug through [Allen brain Explorer](http://help.brain-map.org/display/brainexplorer/Allen+Brain+Explorer+%28beta%29%3A++User+Guide).

**Comment by adamltyson** [comment] 2021-02-03 11:20
Thanks @deepakasaragod, I'd be interested to know the Allen's response.

**Comment by deepakasaragod** [comment] 2021-02-04 15:03
@adamltyson , @FedeClaudi , Just an update, I found this query answered at Allen Forum regarding the  [3d mesh creation](https://community.brain-map.org/t/creating-meshes-from-volumetric-data/509)  by Nile Graddis from Allen. Decimation/Smoothing seems to be the case. 
Will try to get in touch with him and see if there is a way out for fixing this particular issue, although the 'shrinkage' seems not just limited to medial habenula in 3d mesh.
