### ISSUE TITLE
Interactive View Screenshots in Jupyter Notebook

### ISSUE THREAD

**Issue by paulmthompson** [brainglobe/brainrender#91] opened 2020-07-16 14:19 UTC
I can use the code below in a jupyter notebook to create an interactive view embedded in the notebook:

```python
from vtkplotter import *
from brainrender.scene import Scene

embedWindow('panel') 
scene = Scene(jupyter=True) # Create a scene

scene.add_brain_regions(["XII"], colors="ivory", alpha= 0.2, use_original_color=False)

scene.render(interactive = True) # <- this wont actually render things in a notebook

vp = Plotter(axes=0)
vp.show(scene.get_actors())
```
I can take a screenshot of the brain, but I am not able to update the camera for a different view:

```python
scene.take_screenshot() #Image with camera position at 0 1 0

# position 1
bespoke_camera = dict(
    position = [70000, -30000, 50000], # yaw, pitch -30000 or -80000, roll 
    focal = [6587.835, 3849.085, 5688.164],
    viewup = [0, -1.2, 0],
    distance = 61226.68,
    clipping = [47007.899, 79272.88],
)

scene.render(interactive=False,camera=bespoke_camera) #This should move the camera and re-render
scene.take_screenshot() #Image is the same as first image
```
I tried a bunch of permutations of this, and could not get an altered view while using jupyter. From what I can tell, the problem seems to be that the renderer object created with the scene method does not always communicate with the renderer object created for Jupyter. somewhere in this process the camera is always reset to the starting position.

I made the following function to implement camera rotations in the vtkplotter object that is embedded in jupyter. This lets me alter the camera and take new images:

```python
#Modified from https://vtk.org/Wiki/VTK/Examples/Python/Screenshot
import vtk
from brainrender.Utils import camera

#Screen Shot Methods
def take_screenshot2(vp,cam):

    #Change Camera
    camera.set_camera_params(vp.renderer.GetActiveCamera(),cam)
    vp.window.Render()

    w2if = vtk.vtkWindowToImageFilter()
    w2if.SetInput(vp.window)
    w2if.SetInputBufferTypeToRGB()
    w2if.ReadFrontBufferOff()
    w2if.Update()

    writer = vtk.vtkPNGWriter()
    now = datetime.now()
    date_time = now.strftime("%m%d%Y_%H:%M:%S")
    writer.SetFileName(date_time)
    writer.SetInputConnection(w2if.GetOutputPort())
    writer.Write()

#Now I can move the camera and get a screenshot

take_screenshot2(vp,bespoke_camera)
```

What I *really* wanted to do was be able to interact with the 3D brain, set it how I liked, then take a high quality screenshot. These functions below allow me to grab the camera position of the interaction window, and then take a screenshot using that same camera:

```python
def interactive_screenshot(vp):
    new_cam=get_camera_position(settings.notebook_plotter.camera)
    take_screenshot2(vp,new_cam)

def get_camera_position(camera):

    camera_pos = dict(
        position = camera['position'],
        focal = camera['focalPoint'],
        viewup = camera['viewUp'],
        distance = camera['distance'],
        clipping = camera['clippingRange'],
    )
    return camera_pos

```

The method above isn't perfect. I'm only partially transferring options from the interactive view camera, so the screenshots look 95% the same (the screenshots seem to have a smaller FOV), but it's a start.

What would you think of adding this functionality? It may be nice if the jupyter flag you give scene was used to determine which renderer should be used to take a screenshot, but I'm not sure if the scene object has a reference to the vp object to do this.

**Comment by FedeClaudi** [comment] 2020-07-16 14:43
Hi, 
thanks for getting in touch and for the detailed description, and nice work-around for this problem!. 

My first question would be why use notebooks? 
What you're trying to achieve is already implemented in `brainrender`, but as already discussed in other issues not all functionality is supported when embedding scenes in jupyter notebooks. 

The `camera` parameter of the `render` function is among those things that don't seem to work with jupyter yet ([see here](https://github.com/BrancoLab/BrainRender/blob/a929a7889af72f1d0c70e4f9320f71ac7e51155f/brainrender/scene.py#L1099)).

So as you say:
```
scene.render(interactive=False,camera=bespoke_camera) #This should move the camera and re-render
```
except that it doesn't as that doesn't seem to work with the backend that `vedo` uses to embed renderings in notebooks. 
If you were not using notebook then that should work. 

If you do want to use a notebook you could try the following (see https://github.com/BrancoLab/BrainRender/issues/90):
```
from vedo import embedWindow
embedWindow(False) 

```
which will result in the rendering being done in a pop-up window and with a different backend, you might be able to get `scene.render(interactive=False,camera=bespoke_camera)` to work there. 


----

In general I think your solution is really good. I haven't tested it yet but it seems to do what you require so thank you very much for sharing it and I'm sure it might help others too. 

In terms of implementing it in `brainrender`, perhaps [`vedo`](https://github.com/marcomusy/vedo) is a better place for that. `vedo` (developed by the great @marcomusy ) is the package that brainrender relies upon the actual rendering  and given that the problem is not `brainrender`-specific might be the ideal place for this fix.

**Comment by FedeClaudi** [comment] 2020-07-16 14:49
by the way in a development branch I've ended up writing a function similar to your `get_camera_position`  but to get the current camera parameters from the `Scene`. Hopefully this branch will be published soon-ish, but in the meanwhile: 

https://github.com/BrancoLab/BrainRender/blob/ee5d6154ad7b20abc53a50c11302dd431a3b7e61/brainrender/Utils/camera.py#L140

**Comment by paulmthompson** [comment] 2020-07-16 16:06
>> My first question would be why use notebooks?

My big motivator is that jupyter notebooks make it much easier to use containers (e.g. Docker). Since both the coding and the rendering happen in the browser, it is easy to pass around a brainrender docker image to make plots without us having to install python and dependencies. It seems more difficult (I haven't had success at least) to get the right Docker environment that can handle both python coding and opening external windows with plots.

An added bonus is that jupyter compatibility lets us run Brainrender on our jupyterhub server:
https://zero-to-jupyterhub.readthedocs.io/en/latest/

Now members of the lab don't need docker or python; they can just navigate to the server in their web-browser and get started.

I'd be happy to try to make a pull request to your development branch if you'd like.  If I try to imagine a "one-size-fits-all" solution that keeps most of the coding scheme you made without jupyter, I wonder if the vtkplotter object needed for jupyter could be added as a member of the Scene class? So instead of separately requiring the user to create the plotter, the 

```python
vp = Plotter(axes=0)
```
object is a class member of Scene.

If embedded windows are not needed, it wouldn't even need to be initialized, but if jupyter and embedded windows are present, whenever something like scene.render() is called, it could have some boolean checks and instead make some of the workarounds I have above and end with

```python
vp.show(scene.get_actors())
```

This could probably let you use the same code with both jupyter and external windows? I'd be happy to give it a shot. Also let me know if you would want the brainrender docker image to try.

**Comment by FedeClaudi** [comment] 2020-07-16 16:13
Oh wow that's awesome!

I have no experience with docker or jupyter-hub but that sounds great. Sure if you have a docker image I'd be happy to play around with it.

----

> I wonder if the vtkplotter object needed for jupyter could be added as a member of the Scene class

I'm note sure I understand exactly what you mean, but scene already has ` self.plotter` object by default:

https://github.com/BrancoLab/BrainRender/blob/a929a7889af72f1d0c70e4f9320f71ac7e51155f/brainrender/scene.py#L135

however I was not able to use this directly in notebooks. I always had to do create a separate plotter 'in the notebook'  and call `vp.show`. I think it might have to do with stuff happening behind the scenes in `vedo.Plotter` when it's instantiated but I am not sure, perhaps @marcomusy can illuminate us on the subject.


----
I'd be happy to work your suggested code above into brainrender if Marco doesn't think it should go in `vedo`. 
I'm quite busy at the moment, but if you want to work on it and send a PR that could be a great starting point.

**Comment by marcomusy** [comment] 2020-07-19 18:43
Hi guys - sorry for the late reply.. in the case of  `embedWindow('panel')` the whole thing is delegated to `panel` in one single call [here](https://github.com/marcomusy/vedo/blob/cb84f8e47fb5a279a6b8bf50e344f96322659d1c/vedo/backends.py#L259). So one should look at the documentation on how to access the camera after the rendering happened (but it seems that Paul already had success in finding one!).
In the case of `k3d` camera can be modified, I have an example [here](https://github.com/marcomusy/vedo/blob/master/notebooks/basic/manipulate_camera.ipynb). In this case the `show()` does not return a `vedo.Plotter` object but a k3d obj for notebook visualization.

All this might become soon obsolete anyway because the upstream vtk is actively developing new tools for notebooks, so it maybe makes sense to see what happens there before us embarking on developing anything downstream?

**Comment by FedeClaudi** [comment] 2020-07-20 07:12
Hi, 

Thanks Marco! That's very good to know, do you know a rough timeline for the vtk development of notebooks related topics?

**Comment by marcomusy** [comment] 2020-07-20 12:22
i'm not sure about a timeline it seems that notebooks are becoming popular so i think it should be relatively fast!

**Comment by FedeClaudi** [comment] 2020-07-20 12:45
Thanks @marcomusy .

@paulmthompson  I'm happy to go ahead and implement this + work together on a more stable version for docker if you think that'd be a valuable resource to have.

**Comment by paulmthompson** [comment] 2020-07-22 21:40
Sorry I turned this into a multi-part issue!

1. I'll take a look at your development branch and that get_camera_params function. If there is a place to put the interactive screenshot method, I'll make a pull request

2. It looks like the best jupyter solution might be a little complicated since the different backends behave in different ways. I'm happy to close this issue for now and keep our eyes on it to see what changes come our way with Vedo in the near future.

3. I made an example BrainRender docker image for jupyter notebooks. The source code and working image can be found in the following places respectively:
https://github.com/paulmthompson/brainrender-docker
https://hub.docker.com/r/paulmthompson/brainrender-docker

We could probably clone the jupyter examples directory from your repository into an "Examples" folder inside the image to make sure they are all working?

Thanks for the help! I'll close this issue now and let you know if anything comes up.

**Comment by FedeClaudi** [comment] 2020-07-23 08:28
That's awesome, thank you for setting it up. I'll have to play around with it, I'm not very familiar with docker. 

Sounds like a good plan. The 'development branch' should hopefully be released as `brainrender 1.0` by the end of the month. 

Let's keep in touch and see how things progress.

**Comment by marcomusy** [comment] 2020-07-24 09:59
..it's already happening :) 

`pip install ipyvtk_simple`

![image](https://user-images.githubusercontent.com/32848391/88380159-4ee23680-cda4-11ea-8a80-f2cde439f276.png)

Note that the axes as `vtkAsembly` are correctly rendered and the camera positioning is respected

it's still a bit preliminary - eventually the package will land [here](https://github.com/Kitware/ipyvtk)!

**Comment by FedeClaudi** [comment] 2020-07-24 10:13
That looks awesome! 

The only thing we need to make it work is to set `embedWindow = False`, `interactive=False` and then to just pass `plotter.window` to `ViewInteractiveWidget`? 

If so, these are all things that brainrender could take of behind the scenes, making things easier for the users. Is there any downside to this widget? It looks like the resolution might be lower, is there anything in terms of interactivity or things that can be rendered that is limited in?

[I'm reopening so that I don't forget about this :) ]

**Comment by marcomusy** [comment] 2020-07-24 10:21
> The only thing we need to make it work is to set embedWindow = False, interactive=False and then to just pass plotter.window to ViewInteractiveWidget?

I think all this should be managed by `vedo` so all downstream apps dont need to worry - that's should be very easy and painless.

> It looks like the resolution might be lower, 

yes but i think this must be something related anti aliasing by the graphic card, i'm not sure how to change that and if can be dealt with transparently

>  is there anything in terms of interactivity or things that can be rendered that is limited in?

at present `mesh.flag()` (popping up a text tip flag while mouse hovering) dont work... but it's probably a fixable issue.
All the rest should be working like in the native vtk rendering window.

**Comment by FedeClaudi** [comment] 2020-07-24 10:59
That's awesome! Would you might giving me a shout once it's implemented in `vedo` so that I can update the code and docs for `brainrender` please?

**Comment by FedeClaudi** [comment] 2020-10-14 09:54
@paulmthompson  if you're still using `brainrender` in `jupyter` notebooks you might like the new way to embed scenes that @bendichter set up, have a look here: https://github.com/brainglobe/brainrender/blob/master/Examples/notebook_workflow.ipynb

**Comment by nantille** [comment] 2020-11-26 14:33
I'm very interested in that example but the link is broken @FedeClaudi  :p

**Comment by FedeClaudi** [comment] 2020-11-26 15:15
hey, this is the example from Ben:  https://github.com/brainglobe/brainrender/issues/111#issuecomment-706398892
and the notebook is the one you've seen already: https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb

I've recently had some problem with using itkwidgets, but I'm sure that we can fix it. It's a very exciting development and probably the way to go for notebooks

**Closed** 2020-12-08 15:59 UTC
Labels: Jupyter Notebooks, enhancement
