### ISSUE TITLE
Custom PyQt5 brainrender widget

### ISSUE THREAD

**Issue by francesshei** [brainglobe/brainrender#164] opened 2021-06-11 18:09 UTC
Hi all! I guess this can't be really counted as a feature request but it is not a real bug either so I figured I could try and post it here. 

I was able to port a minimal working brainrender widget in a PyQt5 window by looking at the GUI scripts but I'm having a small issue. Specifically, I only copied the code from the App and UI classes  to render the empty 3D model of the mouse atlas (e.g., no actors or camera controls yet), but when I execute the application script it displays both the default plotter as well as my application window. 

The plotter does not update and has no camera click sensitivity, while the QtWidget seems to work perfectly. Moreover, there is no way to close the default plotter other than closing the app itself. 

From what I understood the `setup_plotter` method in the `App` class should avoid this, but it looks like I'm missing something. 
Is there something else I should include in the code in order to force the scene to be rendered within the PyQt window only?

**Comment by FedeClaudi** [comment] 2021-06-11 18:15
Hey, 

It's something I've noticed today as well actually. I don't think it used to be like that, but I'm not 100% sure.
Perhaps something changed in the underlying vedo package (@marcomusy)?

Not sure what the cause is, would have to investigate.

**Comment by francesshei** [comment] 2021-06-11 18:29
Thank you for the quick reply! 

I'll keep developing the app with this extra window opening on the background for now, then. Let me know if you find the cause or a fix for that please! Cheers

**Comment by marcomusy** [comment] 2021-06-13 13:46
Sorry, I cannot see what could be causing that strange behavior.
Indeed I just fixed one possibly related issue here: https://github.com/marcomusy/vedo/issues/409

**Comment by FedeClaudi** [comment] 2021-06-14 07:02
I see, okay it must be a brainrender thing. Thanks for having a look Marco.

**Comment by FedeClaudi** [comment] 2021-06-27 09:47
Should be fixed by https://github.com/brainglobe/brainrender/pull/166 (thanks @francesshei ). 
Will merge into master soon and release a new version

**Comment by FedeClaudi** [comment] 2021-06-27 10:03
Merged to main https://github.com/brainglobe/brainrender/pull/167 and released to a new brainrender version, it's fixed now.
Thank you @francesshei  for the PR.

**Closed by FedeClaudi** 2021-06-27 10:03 UTC
Labels: enhancement
