### ISSUE TITLE
Runtime error?

### ISSUE THREAD

**Issue by seitay** [brainglobe/brainrender#180] opened 2021-11-30 02:20 UTC
Hi,

I wanted to run `brainrender-gui` and I am getting the following error.  Could I be missing installing any python modules?

Thanks,
Seita

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "/usr/local/lib/python3.9/site-packages/pyinspect/exceptions.py", line 79, in render_error
    *inspect_traceback(
  File "/usr/local/lib/python3.9/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "/usr/local/lib/python3.9/site-packages/pyinspect/utils.py", line 135, in read_single_line
    raise FileExistsError(
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/brainrender-gui", line 5, in <module>
    from brainrender.gui.__init__ import clilaunch
  File "/usr/local/lib/python3.9/site-packages/brainrender/__init__.py", line 15, in <module>
    from brainrender.scene import Scene
  File "/usr/local/lib/python3.9/site-packages/brainrender/scene.py", line 18, in <module>
    from brainrender.render import Render
  File "/usr/local/lib/python3.9/site-packages/brainrender/render.py", line 1, in <module>
    from vedo import Plotter, closePlotter
ImportError: cannot import name 'closePlotter' from 'vedo' (/usr/local/lib/python3.9/site-packages/vedo/__init__.py)
```

**Comment by FedeClaudi** [comment] 2021-11-30 08:42
Hi, can you try updating both `vedo` and `brainrender` please? That issue should've been fixed in older versions.

**Comment by raacampbell** [comment] 2021-11-30 16:55
I see the same issue on a fresh `pip install brainrender` I just tried. Upgrading didn't help.

**Comment by seitay** [comment] 2021-11-30 17:20
hi @FedeClaudi I believe I have the latest versions for those two modules but let me know if I have the wrong versions. Thanks.

```
$ pip3 show vedo
Name: vedo
Version: 2021.0.7
Summary: A python module for scientific analysis and visualization of 3D objects and point clouds based on VTK.
Home-page: https://github.com/marcomusy/vedo
Author: Marco Musy
Author-email: marco.musy@embl.es
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: Deprecated, numpy, vtk
Required-by: brainrender, morphapi


$ pip3 show brainrender
Name: brainrender
Version: 2.0.4.1
Summary: Visualisation and exploration of brain atlases and other anatomical data
Home-page: https://github.com/brainglobe/brainrender
Author: Federico Claudi, Adam Tyson, Luigi Petrucco
Author-email: 
License: UNKNOWN
Location: /usr/local/lib/python3.9/site-packages
Requires: bg-atlasapi, k3d, loguru, morphapi, msgpack, myterial, numpy, pandas, pyinspect, pyyaml, qtpy, requests, tables, vedo
Required-by: 
```

**Comment by adamltyson** [comment] 2021-11-30 17:21
@FedeClaudi is this linked to the Python 3.9 discussion on #165? For me this problem only occurs with 3.9, 3.8 is fine.

@seitay, @raacampbell downgrading to Python 3.8 might be a quick fix.

**Comment by FedeClaudi** [comment] 2021-11-30 17:23
I hadn't spotted that it was tested in python 3.9. Yeah @seitay, @raacampbell  can you try downgrading to see if that helps plase?

**Comment by raacampbell** [comment] 2021-12-01 09:42
I get the same error with `3.8.12`. I switched the environment to 3.8 then did `pip install brainrender --upgrade` but get the same issue:

```bash
$ brainrender-gui 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/pyinspect/exceptions.py", line 79, in render_error
    *inspect_traceback(
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/pyinspect/utils.py", line 135, in read_single_line
    raise FileExistsError(
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "/home/rob/miniconda3/envs/brainglobe/bin/brainrender-gui", line 5, in <module>
    from brainrender.gui.__init__ import clilaunch
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/brainrender/__init__.py", line 15, in <module>
    from brainrender.scene import Scene
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/brainrender/scene.py", line 18, in <module>
    from brainrender.render import Render
  File "/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/brainrender/render.py", line 1, in <module>
    from vedo import Plotter, closePlotter
ImportError: cannot import name 'closePlotter' from 'vedo' (/home/rob/miniconda3/envs/brainglobe/lib/python3.8/site-packages/vedo/__init__.py)
(brainglobe) rob@juicer:/mnt/btrfs/cellfinder_test$ python --version
Python 3.8.12

```

**Comment by adamltyson** [comment] 2021-12-01 09:43
@raacampbell do you see the same in a fresh 3.8 env?

**Comment by raacampbell** [comment] 2021-12-01 09:48
> @raacampbell do you see the same in a fresh 3.8 env?

Yes, I do. Is the `vedo` version specified in `setup.py` the correct one?

**Comment by FedeClaudi** [comment] 2021-12-01 10:05
mmm that's weird. Could you try upgrading `vedo`?

**Comment by raacampbell** [comment] 2021-12-01 10:10
I'm already at version `2021.0.7`.

I'm trying to understand what is the origin of the bug and what is the solution. My understanding is that `vedo.closePlotter` was removed at some point. What is the fix in `brainrender` for this and why is it associated with Python 3.8 not 3.9?

**Comment by FedeClaudi** [comment] 2021-12-01 11:22
This issue was reported by adam previously (https://github.com/brainglobe/brainrender/issues/172) and has been fixed here: 19c63b97a34336898871d66fb24484e8a55d4fa7.

Now `brainrender.render.py` doesn't improt `closePlotter` any longer as you can see here: https://github.com/brainglobe/brainrender/blob/master/brainrender/render.py

So I'm not sure why you're getting that error?
Can you try updating brainrender (which version are you currently using?) with `pip install -U brainrender`

**Comment by raacampbell** [comment] 2021-12-01 11:37
Ok, all clear now. It looks like the problem is that pip is giving me brainrender version `2.0.4.1` rather than `2.0.4.5` (what is on PyPi) with both Python 3.9 and Python 3.8.12. `pip install -U brainrender` does not help. Neither does uninstall and reinstall.

**Comment by FedeClaudi** [comment] 2021-12-01 11:48
Mmm werid, I have no idea why it wouldn't update (@adamltyson?)? What if you do: `pip install -U git+https://github.com/brainglobe/brainrender.git`?

**Comment by adamltyson** [comment] 2021-12-01 11:50
I've also got no idea, but it's happened to me before. I just had to tell users to install using the `pip install brainrender==2.0.4.5` syntax and the problem updates after a while.

**Comment by raacampbell** [comment] 2021-12-01 12:07
`pip` seems grumpy about this:

```bash
pip install brainrender==2.0.4.5

```
generates error:
```
ERROR: Could not find a version that satisfies the requirement vtk<=9.0.0 (from brainrender) (from versions: 9.0.1, 9.0.2, 9.0.3, 9.1.0rc1, 9.1.0rc2, 9.1.0rc4, 9.1.0)
ERROR: No matching distribution found for vtk<=9.0.0
```

The same error is generated by:
```
pip install brainrender==2.0.4.2
```

So probably it's installing 2.0.4.1 for me because that's the only version it's happy to install.

**Comment by FedeClaudi** [comment] 2021-12-01 12:32
mmm okay, I'm confused. In python 3.8.0 you should be able to install vtk<=9.0.0, I'm not sure why it's not finding it?

I think that vedo [now supports vtk 9.0](https://github.com/marcomusy/vedo/blob/c33acef0aa9becb5f39404b79b77e75143789695/setup.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L41) so I can try supporting that too in brainrender, it should fix the install error.

**Comment by seitay** [comment] 2021-12-02 01:33
I tried Python 3.8.12 and my issue was rather related to failed installation of `PySide`.

```
Original exception was:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'
```

$ pip install PySide

```
WARNING: Discarding https://files.pythonhosted.org/packages/6b/13/a7f25aceca555549769a3dc29706421a2a6744219616e311c758e807f0d4/PySide-1.1.2.tar.gz#sha256=e7461f66a20bbed9225725a0d485f987840edaedc88a9d3962fd83b673be335f (from https://pypi.org/simple/pyside/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached PySide-1.1.1.tar.gz (9.2 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/setup.py'"'"'; __file__='"'"'/private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-pip-egg-info-99gfmffo
       cwd: /private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/
  Complete output (9 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/setup.py", line 56, in <module>
      from qtinfo import QtInfo
    File "/private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/qtinfo.py", line 3, in <module>
      from popenasync import Popen
    File "/private/var/folders/x2/gmqxhzkn58j7s_bkgvc2xxpxm9ykzp/T/pip-install-lvsflyf6/pyside_c5adbb3c7d6040e2b72e06ce51b8c399/popenasync.py", line 26, in <module>
      if subprocess.mswindows:
  AttributeError: module 'subprocess' has no attribute 'mswindows'
```

**Comment by raacampbell** [comment] 2021-12-02 10:32
FWIW, I'm on conda 4.10.3 and I can't install PySide at all. It errors with:

```
from https://pypi.org/simple/pyside/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyside (from versions: 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.4)
ERROR: No matching distribution found for pyside

```

**Comment by FedeClaudi** [comment] 2021-12-02 12:47
Brainrender doesn't install `PySide` directly, is that due to `qtpy`? (hard to say from the limited traceback provided). 
Brainrender gives the [option](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/setup.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L87) to install `PySide2` for the GUI functionality, but that's not installed by default.

@raacampbell  the error above was about `vtk`, why are you trying to install `PySide`?

**Comment by FedeClaudi** [comment] 2021-12-02 12:52
@raacampbell  I've opened a new branc `vtk9` which supports up to `vtk==9.1.0` so that should resolve your issue. You can try installing it with: `pip install -U git+https://github.com/brainglobe/brainrender.git@vtk9`, let me know if that works or if newer version of `vtk` cause problems.

**Comment by raacampbell** [comment] 2021-12-02 13:05
The `vtk9` branch works, yes, thanks.

**Comment by seitay** [comment] 2021-12-02 16:52
> Brainrender doesn't install `PySide` directly, is that due to `qtpy`? (hard to say from the limited traceback provided). Brainrender gives the [option](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/setup.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L87) to install `PySide2` for the GUI functionality, but that's not installed by default.
> 
> @raacampbell the error above was about `vtk`, why are you trying to install `PySide`?

Yes, I believe so.  Here is the full traceback.

```
% /usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/bin/brainrender-gui 


Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/pyinspect/exceptions.py", line 79, in render_error
    *inspect_traceback(
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/pyinspect/utils.py", line 135, in read_single_line
    raise FileExistsError(
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/bin/brainrender-gui", line 5, in <module>
    from brainrender.gui.__init__ import clilaunch
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/brainrender/gui/__init__.py", line 1, in <module>
    from qtpy.QtWidgets import QApplication
  File "/usr/local/var/pyenv/versions/3.8.12/envs/brainrender_3812/lib/python3.8/site-packages/qtpy/__init__.py", line 216, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by seitay** [comment] 2021-12-03 00:40
Tried `vtk9` branch.  Seems like same PySide error.  Did I miss anything?

```
$ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/bin/brainrender-gui


Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/pyinspect/exceptions.py", line 79, in render_error
    *inspect_traceback(
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/pyinspect/utils.py", line 135, in read_single_line
    raise FileExistsError(
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/qtpy/__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/bin/brainrender-gui", line 5, in <module>
    from brainrender.gui.__init__ import clilaunch
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/gui/__init__.py", line 1, in <module>
    from qtpy.QtWidgets import QApplication
  File "/usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/qtpy/__init__.py", line 216, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

```
$ pip freeze | grep vtk

vtk==9.0.3
```

**Comment by FedeClaudi** [comment] 2021-12-03 09:54
The vtk branch was for a separate problem. 
Can you try `pip install PySide2`?

**Comment by seitay** [comment] 2021-12-03 17:45
thanks @FedeClaudi PySide2 worked.

**Comment by seitay** [comment] 2021-12-07 00:20
I'm not sure if related to [https://github.com/brainglobe/brainrender/issues/181](https://github.com/brainglobe/brainrender/issues/181), I was not able to load `.swc` file with the latest version.  The following is the error I observed.  I tried the dataset from [https://github.com/brainglobe/morphapi/tree/master/examples/example_files](https://github.com/brainglobe/morphapi/tree/master/examples/example_files) and several samples and they show the same errors.

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/gui │
│ /apputils/add_from_file_control.py:79 in add_from_file_object                                    │
│                                                                                                  │
│   76 │   │   Method of the corresponding button                                                  │
│   77 │   │   """                                                                                 │
│   78 │   │   logger.debug("GUI: adding mesh (e.g. obj) form file")                               │
│ ❱ 79 │   │   self.__add_from_file(self.scene.add)                                                │
│   80 │                                                                                           │
│   81 │   def _get_cells_mesh(self, fp):                                                          │
│   82 │   │   data = np.load(fp)                                                                  │
│ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/gui │
│ /apputils/add_from_file_control.py:56 in __add_from_file                                         │
│                                                                                                  │
│   53 │   │   │   color = get_color_from_string(dialog.color_textbox.text())                      │
│   54 │   │   │                                                                                   │
│   55 │   │   │   # Add actor                                                                     │
│ ❱ 56 │   │   │   act = fun(fname)                                                                │
│   57 │   │   │   if not isinstance(act, (tuple, list)):                                          │
│   58 │   │   │   │   act = [act]                                                                 │
│   59                                                                                             │
│                                                                                                  │
│ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/sce │
│ ne.py:166 in add                                                                                 │
│                                                                                                  │
│   163 │   │   │   │   actors.append(item)                                                        │
│   164 │   │   │                                                                                  │
│   165 │   │   │   elif isinstance(item, (str, Path)):                                            │
│ ❱ 166 │   │   │   │   mesh = load_mesh_from_file(item, **kwargs)                                 │
│   167 │   │   │   │   name = name or Path(item).name                                             │
│   168 │   │   │   │   _class = _class or "from file"                                             │
│   169 │   │   │   │   actors.append(Actor(mesh, name=name, br_class=_class))                     │
│                                                                                                  │
│ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/_io │
│ .py:70 in inner                                                                                  │
│                                                                                                  │
│   67 │   │   │   raise FileNotFoundError(                                                        │
│   68 │   │   │   │   f"File {args[0]} not found"                                                 │
│   69 │   │   │   )  # pragma: no cover                                                           │
│ ❱ 70 │   │   return func(*args, **kwargs)                                                        │
│   71 │                                                                                           │
│   72 │   return inner                                                                            │
│   73                                                                                             │
│                                                                                                  │
│ /usr/local/var/pyenv/versions/3.9.9/envs/brainrender/lib/python3.9/site-packages/brainrender/_io │
│ .py:85 in load_mesh_from_file                                                                    │
│                                                                                                  │
│   82 │                                                                                           │
│   83 │   """                                                                                     │
│   84 │   actor = load(str(filepath))                                                             │
│ ❱ 85 │   actor.c(color).alpha(alpha)                                                             │
│   86 │   return actor                                                                            │
│   87                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'c'
```

**Comment by FedeClaudi** [comment] 2021-12-08 08:34
[load_mesh_from_file](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/brainrender/_io.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L76) only supports loading of `.obj` and `.stl` files (and a couple others supported by `vedo`). 
The GUI currently doesn't have a way to load `.swc` data into it, though ti would be fairly easy to expand `load_mesh_from_file` to use the [`Neuron`](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/brainrender/actors/neurons.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L35) class to load neurons when a path to an `.swc` is passed, if you want to try creating a pull request with this new feature.

**Comment by seitay** [comment] 2021-12-09 01:01
@FedeClaudi I wanted to check if I can render as described [here](https://www.biorxiv.org/content/10.1101/2020.02.23.961748v1.full#F1) in Fig 1c and Fig 1d.  I may have confused with loading `.swc` files instead of `.obj` or `.stl`.  Do you have a working example I can check to visualize on the brainrender GUI? 

[https://www.biorxiv.org/content/10.1101/2020.02.23.961748v1.full#F1](https://www.biorxiv.org/content/10.1101/2020.02.23.961748v1.full#F1)
```
Mesoscale connectivity data from the Mouse Connectome project can be visualised in two ways: 
1) efferent projections can be rendered as streamlines (Fig 1c) and 2) afferent 
projections can be visualised as tractography data (Fig 1d).
```
```
To visualise afferent projections to a region of interests, brainrender selects the set of tracing 
experiments in the Mouse Connectome project that resulted in fluorescence signal in the 
selected region by using the Allen institute’s SDK and API services. Then, the location of virus 
injection of each selected experiment and the projections to the region of interest are rendered 
as displayed in Fig. 1d.
```
Thanks.

**Comment by FedeClaudi** [comment] 2021-12-09 10:21
it seems that you're looking at an old version of the preprint, this is the final article: https://elifesciences.org/articles/65751.

We have removed the mesocale connectivity visualization since it was hardly ever used, so figure 1d from the old preprint is no longer possible (by default in brainrender, though it would be simple enough to make on your own if interested). Figure 1c shows a streamlines visualization of efferent connections, and there's an [example](https://github.com/brainglobe/brainrender/blob/master/examples/streamlines.py) for how to do that in brainrender.
Figure 1e,f shows single neurons visualizations from .swc files, and there's an [example](https://github.com/brainglobe/brainrender/blob/master/examples/neurons.py) for that too.

**Closed** 2021-12-28 18:52 UTC
